### PR TITLE
Added the journal entry 2 file and the css file

### PR DESCRIPTION
**Pull request by jorgehjr84**

### CODE REVIEW

**Comment by pcreglow** [comment]
Good start! I have similar thoughts and struggles. :+1:

**Comment by kmattiko** [comment]
I see you already had two people thumbs up before I got the chance :stuck_out_tongue_winking_eye: Good start to a week two journal entry though! :+1:

**Comment by JessyRiordan** [comment]
:+1:  I love that when you get stuck you spend time with your son.... this makes me smile!

**Comment by gatorpazz** [comment]
I like the code examples used in your journal, pretty high speed, 10/10, would read again :+1:

**Comment by sjoyal** [comment]
Good journal my man. I like the stuff you added about scope. I would look into the scrolling that's going on in your code blocks. :+1:

**Comment by melrodbos** [comment]
Another :+1: to add to your repertoire. Great read and very interesting perspective on scoping.

**Pull request merged**
