### PR TITLE
yak shaving. Installed Boilerplate, and .json files

### PR DESCRIPTION
**Pull request by jorgehjr84**
- **HALFTIME Journal**
  - [x] Time for some `remodeling`...
  - [x] Moving day, `_posts`...!
  - [x] You got that `yo h5bp`?
  - [x] Bower and NPM, back in the saddle.
  - [ ] Browser? Sync'd.
  - [ ] Skitched that layout?
  - [ ] Breakpoints?
  - [ ] Made a plan...
  - [ ] Wrote it down...
  - [ ] Broke it up...
- **HALFTIME Journal**
  - [ ] First feature:
- [ ] Header(created the all of the html skeleton for the header, along with styling
- [ ] Added Content to the header's individual elements
  - [ ] Committed and pushed!
  - [ ] PR open!
  - [ ] PR merged!
    --1 pomodoro-- (5:00pm)
  - [ ] Second feature:
  - [ ] Created the html skeleton for the content section of the homepage
  - [ ] Added individual sections for logo/ Name/ and title in the content section
  - [ ] Style the content to play nice with each other and look good together
    - [ ] Committed and pushed!
    - [ ] PR open!
    - [ ] PR merged!
      --3 pomodoros-- (5:30pm)
  - [ ] Third feature:
  - [ ]  Image for header dropped in
  - [ ] Background image correct size
  - [ ] Committed and pushed!
  - [ ] PR open!
  - [ ] PR merged!
    --1 pomodoro-- (8:00pm)
  - [ ] **BEAST MODE** Journal entry draft...

### CODE REVIEW

**Comment by jorgehjr84** [comment]
HALFTIME Journal
 Time for some remodeling...
 Moving day, _posts...!
 You got that yo h5bp?
 Bower and NPM, back in the saddle.
 Browser? Sync'd.
 Skitched that layout?
 Breakpoints?
 Made a plan...
 Wrote it down...
 Broke it up...
Blueprints Everywhere!
 Burnin' down the house!
 Yo. H5BP, yo. Hey, yo, H5BP.
 Skitchers gonna Skitch.
 Planners gonna plan.
 Yak shaved.

**Comment by al-the-x** [comment]
Do yourself a favor and link to the template you're using... maybe even the demo site.

**Comment by jorgehjr84** [comment]
Link to Bootstrap template

http://themes.startbootstrap.com/vitality-v1.3.4/creative.html

**Comment by al-the-x** [comment]
This will be challenging. Please be very explicit in breaking down the features and decide on some that you can live without.

**Comment by al-the-x** [comment]
Your planning checklist is a little wonky...Formatting?

**Comment by al-the-x** [comment]
As we discussed in class, you should break down that template more... There's a _lot_ in there. Get a screenie of _each_ section and name them prefixed with numbers to get them to stay in order... like the class assignments. And don't neglect the breakpoints, either. Each of those "widgets" changes dependent on the size of the viewport. O_O

**Pull request merged**
