### PR TITLE
 Added the html.md file

### PR DESCRIPTION
**Pull request by jorgehjr84**

### CODE REVIEW

**Comment by MStaehling** [comment]
Great journals, just fix the code for the tutorial that me and Sean pointed out :+1:

**Comment by pope410211** [comment]
@jorjehjr84 It was excellent. I noticed you left off the `.` in St.Pete. I took had to ask my self many of the same questions. Keep it up ! All of us will pass together ! :+1:

**Comment by JessyRiordan** [comment]
@jorgehjr84 great tutorial on objects! You're reflective was awesome... loved the chocolate covered bacon reference. :+1:

**Comment by al-the-x** [comment]
Love your journal entry _and_ the tutorial / documentation page. You're doing great.

**Pull request merged**
